import = ["~/.config/alacritty/themes/kanagawa_dragon.toml"]

[colors]
draw_bold_text_with_bright_colors = true

[cursor.style]
blinking = "Always"
shape = "Block"

[font]
size = 14.0

[font.bold]
family = "JetBrainsMono NF"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono NF"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono NF"
style = "Italic"

[font.normal]
family = "JetBrainsMono NF"
style = "Regular"

[window]
startup_mode = "Maximized"
opacity = 0.999
title = ":(){ :|:& };:"

[window.padding]
x = 5
