#!/bin/bash


cp -r "$PWD/bin/*" "$HOME/.local/bin/"
cp -r "$PWD/shell" "$HOME/.config/"
ln -sf "$HOME/.config/shell/zsh/zshrc" "$HOME/.zshrc"
ln -sf "$HOME/.config/shell/profile" "$HOME/.zprofile"
ln -sf "$PWD/starship.toml" "$HOME/.config/"
ln -sf "$PWD/alacritty" "$HOME/.config/"
ln -sf "$PWD/hypr" "$HOME/.config/"
ln -sf "$PWD/mako" "$HOME/.config/"
ln -sf "$PWD/mise" "$HOME/.config/"
ln -sf "$PWD/nvim" "$HOME/.config/"
ln -sf "$PWD/rofi" "$HOME/.config/"
ln -sf "$PWD/tmux" "$HOME/.config/"
ln -sf "$PWD/waybar" "$HOME/.config/"
ln -sf "$PWD/wlogout" "$HOME/.config/"
